apiVersion: 1

deleteDatasources:
  - name: ".ds-app-logs-*"
    orgId: 1

datasources:
  # Elasticsearch for logs
  - name: Elasticsearch-Logs
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: ".ds-app-logs-*"
    isDefault: false
    jsonData:
      timeField: "@timestamp"
      esVersion: "9.0.0"
      logMessageField: message
      logLevelField: log.level
    editable: true

  # Prometheus for metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: "15s"
    editable: true
