"""Initial migration

Revision ID: 5e620ad41150
Revises: 
Create Date: 2025-10-17 11:41:04.558979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e620ad41150'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessory_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('ma_phu_kien', sa.String(), nullable=False),
    sa.Column('ten_phu_kien', sa.String(), nullable=False),
    sa.Column('so_luong', sa.Integer(), nullable=False),
    sa.Column('ten_khach_hang', sa.String(), nullable=False),
    sa.Column('so_dien_thoai', sa.String(), nullable=False),
    sa.Column('dia_chi', sa.Text(), nullable=False),
    sa.Column('loai_don_hang', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessory_orders_customer_id'), 'accessory_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_accessory_orders_id'), 'accessory_orders', ['id'], unique=False)
    op.create_index(op.f('ix_accessory_orders_order_id'), 'accessory_orders', ['order_id'], unique=True)
    op.create_index(op.f('ix_accessory_orders_thread_id'), 'accessory_orders', ['thread_id'], unique=False)
    op.create_table('chat_customers',
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_chat_customers_customer_id'), 'chat_customers', ['customer_id'], unique=False)
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('thread_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_history_customer_id'), 'chat_history', ['customer_id'], unique=False)
    op.create_index(op.f('ix_chat_history_id'), 'chat_history', ['id'], unique=False)
    op.create_index(op.f('ix_chat_history_thread_id'), 'chat_history', ['thread_id'], unique=False)
    op.create_table('chat_threads',
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('thread_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id', 'thread_id')
    )
    op.create_index(op.f('ix_chat_threads_customer_id'), 'chat_threads', ['customer_id'], unique=False)
    op.create_index(op.f('ix_chat_threads_thread_id'), 'chat_threads', ['thread_id'], unique=False)
    op.create_table('chatbot_settings',
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('chatbot_icon_url', sa.String(), nullable=True),
    sa.Column('chatbot_message_default', sa.String(), nullable=True),
    sa.Column('chatbot_callout', sa.String(), nullable=True),
    sa.Column('chatbot_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_chatbot_settings_customer_id'), 'chatbot_settings', ['customer_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('full_content', sa.Text(), nullable=True),
    sa.Column('file_content', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_customer_id'), 'documents', ['customer_id'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('product_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('ma_san_pham', sa.String(), nullable=False),
    sa.Column('ten_san_pham', sa.String(), nullable=False),
    sa.Column('so_luong', sa.Integer(), nullable=False),
    sa.Column('ten_khach_hang', sa.String(), nullable=False),
    sa.Column('so_dien_thoai', sa.String(), nullable=False),
    sa.Column('dia_chi', sa.Text(), nullable=False),
    sa.Column('loai_don_hang', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_orders_customer_id'), 'product_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_product_orders_id'), 'product_orders', ['id'], unique=False)
    op.create_index(op.f('ix_product_orders_order_id'), 'product_orders', ['order_id'], unique=True)
    op.create_index(op.f('ix_product_orders_thread_id'), 'product_orders', ['thread_id'], unique=False)
    op.create_table('service_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('ma_dich_vu', sa.String(), nullable=False),
    sa.Column('ten_dich_vu', sa.String(), nullable=False),
    sa.Column('loai_dich_vu', sa.String(), nullable=True),
    sa.Column('ten_san_pham_sua_chua', sa.String(), nullable=False),
    sa.Column('ten_khach_hang', sa.String(), nullable=False),
    sa.Column('so_dien_thoai', sa.String(), nullable=False),
    sa.Column('dia_chi', sa.Text(), nullable=False),
    sa.Column('loai_don_hang', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_orders_customer_id'), 'service_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_service_orders_id'), 'service_orders', ['id'], unique=False)
    op.create_index(op.f('ix_service_orders_order_id'), 'service_orders', ['order_id'], unique=True)
    op.create_index(op.f('ix_service_orders_thread_id'), 'service_orders', ['thread_id'], unique=False)
    op.create_table('store_info',
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('store_name', sa.String(), nullable=True),
    sa.Column('store_address', sa.String(), nullable=True),
    sa.Column('store_phone', sa.String(), nullable=True),
    sa.Column('store_email', sa.String(), nullable=True),
    sa.Column('store_website', sa.String(), nullable=True),
    sa.Column('store_facebook', sa.String(), nullable=True),
    sa.Column('store_address_map', sa.String(), nullable=True),
    sa.Column('store_image', sa.String(), nullable=True),
    sa.Column('info_more', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_store_info_customer_id'), 'store_info', ['customer_id'], unique=False)
    op.create_table('system_instructions',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_system_instructions_key'), 'system_instructions', ['key'], unique=False)
    op.drop_index(op.f('ix_session_controls_customer_id'), table_name='session_controls')
    op.drop_index(op.f('ix_session_controls_id'), table_name='session_controls')
    op.drop_index(op.f('ix_session_controls_session_id'), table_name='session_controls')
    op.drop_table('session_controls')
    op.add_column('customer_is_sale', sa.Column('is_sale_customer', sa.Boolean(), nullable=False))
    op.drop_column('customer_is_sale', 'is_sale')
    op.add_column('customers', sa.Column('ai_name', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('ai_role', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('custom_prompt', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('service_feature_enabled', sa.Boolean(), nullable=True))
    op.add_column('customers', sa.Column('accessory_feature_enabled', sa.Boolean(), nullable=True))
    op.add_column('customers', sa.Column('product_feature_enabled', sa.Boolean(), nullable=True))
    op.drop_column('customers', 'store_phone')
    op.drop_column('customers', 'store_address')
    op.drop_column('customers', 'store_address_map')
    op.drop_column('customers', 'store_image')
    op.drop_column('customers', 'store_website')
    op.drop_column('customers', 'store_name')
    op.drop_column('customers', 'store_facebook')
    op.drop_column('customers', 'info_more')
    op.drop_column('customers', 'store_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('store_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('info_more', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('store_facebook', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('store_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('store_website', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('store_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('store_address_map', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('store_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('store_phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('customers', 'product_feature_enabled')
    op.drop_column('customers', 'accessory_feature_enabled')
    op.drop_column('customers', 'service_feature_enabled')
    op.drop_column('customers', 'custom_prompt')
    op.drop_column('customers', 'ai_role')
    op.drop_column('customers', 'ai_name')
    op.add_column('customer_is_sale', sa.Column('is_sale', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('customer_is_sale', 'is_sale_customer')
    op.create_table('session_controls',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('session_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('session_controls_pkey'))
    )
    op.create_index(op.f('ix_session_controls_session_id'), 'session_controls', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_controls_id'), 'session_controls', ['id'], unique=False)
    op.create_index(op.f('ix_session_controls_customer_id'), 'session_controls', ['customer_id'], unique=False)
    op.drop_index(op.f('ix_system_instructions_key'), table_name='system_instructions')
    op.drop_table('system_instructions')
    op.drop_index(op.f('ix_store_info_customer_id'), table_name='store_info')
    op.drop_table('store_info')
    op.drop_index(op.f('ix_service_orders_thread_id'), table_name='service_orders')
    op.drop_index(op.f('ix_service_orders_order_id'), table_name='service_orders')
    op.drop_index(op.f('ix_service_orders_id'), table_name='service_orders')
    op.drop_index(op.f('ix_service_orders_customer_id'), table_name='service_orders')
    op.drop_table('service_orders')
    op.drop_index(op.f('ix_product_orders_thread_id'), table_name='product_orders')
    op.drop_index(op.f('ix_product_orders_order_id'), table_name='product_orders')
    op.drop_index(op.f('ix_product_orders_id'), table_name='product_orders')
    op.drop_index(op.f('ix_product_orders_customer_id'), table_name='product_orders')
    op.drop_table('product_orders')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_customer_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_chatbot_settings_customer_id'), table_name='chatbot_settings')
    op.drop_table('chatbot_settings')
    op.drop_index(op.f('ix_chat_threads_thread_id'), table_name='chat_threads')
    op.drop_index(op.f('ix_chat_threads_customer_id'), table_name='chat_threads')
    op.drop_table('chat_threads')
    op.drop_index(op.f('ix_chat_history_thread_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_customer_id'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index(op.f('ix_chat_customers_customer_id'), table_name='chat_customers')
    op.drop_table('chat_customers')
    op.drop_index(op.f('ix_accessory_orders_thread_id'), table_name='accessory_orders')
    op.drop_index(op.f('ix_accessory_orders_order_id'), table_name='accessory_orders')
    op.drop_index(op.f('ix_accessory_orders_id'), table_name='accessory_orders')
    op.drop_index(op.f('ix_accessory_orders_customer_id'), table_name='accessory_orders')
    op.drop_table('accessory_orders')
    # ### end Alembic commands ###
