"""extract prompt

Revision ID: 97d2e6e074f5
Revises: 5e620ad41150
Create Date: 2025-10-22 09:18:30.151949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97d2e6e074f5'
down_revision: Union[str, Sequence[str], None] = '5e620ad41150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_prompt_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('persona_template', sa.Text(), nullable=True),
    sa.Column('tone_style', sa.Text(), nullable=True),
    sa.Column('workflow_header', sa.Text(), nullable=True),
    sa.Column('base_instructions', sa.Text(), nullable=True),
    sa.Column('product_workflow', sa.Text(), nullable=True),
    sa.Column('service_workflow', sa.Text(), nullable=True),
    sa.Column('accessory_workflow', sa.Text(), nullable=True),
    sa.Column('workflow_instructions', sa.Text(), nullable=True),
    sa.Column('pagination_instruction', sa.Text(), nullable=True),
    sa.Column('faq_instruction', sa.Text(), nullable=True),
    sa.Column('faq_context_template', sa.Text(), nullable=True),
    sa.Column('ocr_instruction', sa.Text(), nullable=True),
    sa.Column('ocr_prefix_label', sa.String(), nullable=True),
    sa.Column('chat_history_role_user', sa.String(), nullable=True),
    sa.Column('chat_history_role_ai', sa.String(), nullable=True),
    sa.Column('tool_retrieve_document_description', sa.Text(), nullable=True),
    sa.Column('tool_check_customer_info_description', sa.Text(), nullable=True),
    sa.Column('tool_get_store_info_description', sa.Text(), nullable=True),
    sa.Column('tool_search_products_description', sa.Text(), nullable=True),
    sa.Column('tool_create_order_product_description', sa.Text(), nullable=True),
    sa.Column('tool_search_services_description', sa.Text(), nullable=True),
    sa.Column('tool_create_order_service_description', sa.Text(), nullable=True),
    sa.Column('tool_search_accessories_description', sa.Text(), nullable=True),
    sa.Column('tool_create_order_accessory_description', sa.Text(), nullable=True),
    sa.Column('tool_escalate_to_human_response', sa.Text(), nullable=True),
    sa.Column('tool_end_conversation_response', sa.Text(), nullable=True),
    sa.Column('filter_results_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_prompt_profiles_customer_id'), 'system_prompt_profiles', ['customer_id'], unique=False)
    op.create_index(op.f('ix_system_prompt_profiles_id'), 'system_prompt_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_prompt_profiles_id'), table_name='system_prompt_profiles')
    op.drop_index(op.f('ix_system_prompt_profiles_customer_id'), table_name='system_prompt_profiles')
    op.drop_table('system_prompt_profiles')
    # ### end Alembic commands ###
