"""add graphrag_artifacts

Revision ID: 994af86b7866
Revises: 97d2e6e074f5
Create Date: 2025-10-29 14:08:51.170214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '994af86b7866'
down_revision: Union[str, Sequence[str], None] = '97d2e6e074f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graphrag_artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('artifact_type', sa.String(), nullable=False),
    sa.Column('row_id', sa.String(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graphrag_artifacts_customer_id'), 'graphrag_artifacts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_graphrag_artifacts_id'), 'graphrag_artifacts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graphrag_artifacts_id'), table_name='graphrag_artifacts')
    op.drop_index(op.f('ix_graphrag_artifacts_customer_id'), table_name='graphrag_artifacts')
    op.drop_table('graphrag_artifacts')
    # ### end Alembic commands ###
