from fastapi import APIRouter, HTTPException, BackgroundTasks
from pydantic import BaseModel
from typing import Optional
from pathlib import Path

from service.graphrag.graphrag_service import (
    workspace_path_for_customer,
    ensure_workspace_initialized,
    upsert_env_api_key,
    export_documents,
    run_index,
    persist_output_to_db,
    configure_models_gemini,
    configure_input_for_json,
    configure_cache_short_base,
)
from database.database import SessionLocal


router = APIRouter()


class GraphRAGIndexRequest(BaseModel):
    api_key: str
    method: Optional[str] = "standard"
    persist_to_db: Optional[bool] = True
    overwrite: Optional[bool] = True
    provider: Optional[str] = "openai"  # "openai" | "gemini"
    chat_model: Optional[str] = None     # e.g., "gemini-2.5-flash"
    embedding_model: Optional[str] = None  # e.g., "gemini-embedding-001"


def _background_reindex(
    customer_id: str,
    api_key: str,
    method: Optional[str],
    persist_to_db: bool,
    overwrite: bool,
    provider: Optional[str],
    chat_model: Optional[str],
    embedding_model: Optional[str],
):
    root: Path = workspace_path_for_customer(customer_id)
    ensure_workspace_initialized(root)
    if (provider or "openai").lower() == "gemini":
        # Configure Gemini via LiteLLM in settings.yaml and set GEMINI_API_KEY
        configure_models_gemini(
            root,
            chat_model=chat_model or "gemini-2.5-flash",
            embedding_model=embedding_model or "gemini-embedding-001",
        )
        if api_key:
            upsert_env_api_key(root, api_key, env_key="GEMINI_API_KEY")
    else:
        # Default path assumes OpenAI config generated by graphrag init uses GRAPHRAG_API_KEY
        if api_key:
            upsert_env_api_key(root, api_key, env_key="GRAPHRAG_API_KEY")
    # Shorten cache path and precreate common cache dirs to prevent FileNotFoundError / MAX_PATH issues on Windows
    configure_cache_short_base(root)
    db = SessionLocal()
    try:
        # Ensure the pipeline loads JSON from input/ (documents.json) instead of .txt only
        configure_input_for_json(root)
        export_documents(db, customer_id, root)
    finally:
        db.close()
    ok = run_index(root, method or "standard")
    if not ok:
        # write a small marker so users can find the CLI log quickly
        try:
            marker = (root / "logs" / "INDEX_FAILED.txt")
            marker.parent.mkdir(parents=True, exist_ok=True)
            with marker.open("w", encoding="utf-8") as f:
                f.write("Indexing failed. See cli_index.log in this folder for details.\n")
        except Exception:
            pass
        return
    if persist_to_db:
        db2 = SessionLocal()
        try:
            persist_output_to_db(db2, customer_id, root, overwrite=overwrite)
        finally:
            db2.close()


@router.post("/graphrag/reindex/{customer_id}")
async def reindex(customer_id: str, data: GraphRAGIndexRequest, background: BackgroundTasks):
    try:
        root: Path = workspace_path_for_customer(customer_id)
        background.add_task(
            _background_reindex,
            customer_id,
            data.api_key,
            data.method,
            data.persist_to_db if data.persist_to_db is not None else True,
            data.overwrite if data.overwrite is not None else True,
            data.provider if data.provider is not None else "openai",
            data.chat_model,
            data.embedding_model,
        )
        return {"status": "accepted", "workspace": str(root)}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
